### ISSUE TITLE
IDEN Command Fails when not given username

### ISSUE THREAD

**Issue by cwkang1998** [cwkang1998/SQA_Coursework#3]
The IDEN command would cause the server to throw a `StringIndexOutOfBoundsException`  when no username is provided after the IDEN keyword.

```bash
Exception in thread "Thread-5" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1931)
	at g53sqm.chat.server.Connection.validateMessage(Connection.java:67)
	at g53sqm.chat.server.Connection.run(Connection.java:45)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by cwkang1998** [comment]
This will now be close in favor of #4
