### ISSUE TITLE
Parameterized server command fails when given a empty username

### ISSUE THREAD

**Issue by cwkang1998** [cwkang1998/SQA_Coursework#4]
The IDEN, HAIL and MESG command would cause the server to throw a `ArrayIndexOutOfBoundException` when provided with an empty string as username.

```
Exception in thread "Thread-5" java.lang.ArrayIndexOutOfBoundsException: 0
	at g53sqm.chat.server.Connection.iden(Connection.java:129)
	at g53sqm.chat.server.Connection.validateMessage(Connection.java:67)
	at g53sqm.chat.server.Connection.run(Connection.java:45)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by cwkang1998** [comment]
It is found that this issue also appears in other commands that accepts parameters, so extending this issue.
Also since this issue is of the same nature with #3 , we shall close that in favor of this one.
